name: public
named: {}
views:
  demo/zefix.login: true
collections: {}
routes:
  demo/zefix.login: true
  demo/zefix.requestpassword: true
files:
  demo/zefix.thirty3logo: true
  demo/zefix.thirty3web: true
  demo/zefix.uesio_logo_2: true
  demo/zefix.uesio_logo1: true
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: false
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
